on:
  push:
    tags:
      - 'core-v*'
  workflow_dispatch:

jobs:
  build-core:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: pwsh
      - name: Validate
        run: .\build\vsts-validate.ps1
        shell: pwsh
      - name: Build Core
        run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
        shell: pwsh
        env:
          APIKEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
